export const jerry = [
  "*akcencik*",
  "To już było",
  "Kończymy wcześniej",
  "Panowie przeginka",
  "Kahoot",
  "AI",
  "Panowie powaga",
  "6 za aktywność",
  "Możemy tak zrobić?",
  "Unit X test",
  "Ja rozumiem ale nie możemy tak",
  "Orgasmus",
  "Time managment",
  "To co za tydzień klasóweczka",
  "Panowie znacie te słowo?",
  "Dżentelmeńska umowa",
  "Wyjazd",
  "Corn Dogi",
  "Cyfrowe Państwo - Marcin Kowalczyk",
  "Schowajcie telefony",
  "Ja mam sprawdzian przygotowany moge dać",
  "Chłopaki szanujmy sie",
  "",
];
